// src/app.ts
import express from "express";
import { toNodeHandler } from "better-auth/node";

// src/app/routes/index.ts
import { Router as Router5 } from "express";

// src/app/modules/post/post.routes.ts
import { Router } from "express";

// src/app/utils/catchAsync.ts
var catchAsync = (fn) => (req, res, next) => {
  Promise.resolve(fn(req, res, next)).catch(next);
};

// src/generated/prisma/enums.ts
var Role = {
  USER: "USER",
  ADMIN: "ADMIN"
};
var Privacy = {
  PUBLIC: "PUBLIC",
  PRIVATE: "PRIVATE"
};

// src/app/lib/prisma.ts
import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";

// src/generated/prisma/client.ts
import * as path from "path";
import { fileURLToPath } from "url";

// src/generated/prisma/internal/class.ts
import * as runtime from "@prisma/client/runtime/client";
var config = {
  "previewFeatures": [],
  "clientVersion": "7.4.2",
  "engineVersion": "94a226be1cf2967af2541cca5529f0f7ba866919",
  "activeProvider": "postgresql",
  "inlineSchema": 'model User {\n  id               String             @id\n  name             String\n  email            String\n  emailVerified    Boolean            @default(false)\n  image            String?\n  createdAt        DateTime           @default(now())\n  updatedAt        DateTime           @updatedAt\n  role             String             @default("USER")\n  status           String             @default("ACTIVE")\n  changePassword   Boolean            @default(false)\n  isDeleted        Boolean?           @default(false)\n  deletedAt        DateTime?\n  sessions         Session[]\n  accounts         Account[]\n  posts            Post[]\n  comments         Comment[]\n  commentReactions CommentReactions[]\n  postReactions    PostReactions[]\n\n  @@unique([email])\n  @@map("user")\n}\n\nmodel Session {\n  id        String   @id\n  expiresAt DateTime\n  token     String\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n  ipAddress String?\n  userAgent String?\n  userId    String\n  user      User     @relation(fields: [userId], references: [id], onDelete: Cascade)\n\n  @@unique([token])\n  @@index([userId])\n  @@map("session")\n}\n\nmodel Account {\n  id                    String    @id\n  accountId             String\n  providerId            String\n  userId                String\n  user                  User      @relation(fields: [userId], references: [id], onDelete: Cascade)\n  accessToken           String?\n  refreshToken          String?\n  idToken               String?\n  accessTokenExpiresAt  DateTime?\n  refreshTokenExpiresAt DateTime?\n  scope                 String?\n  password              String?\n  createdAt             DateTime  @default(now())\n  updatedAt             DateTime  @updatedAt\n\n  @@index([userId])\n  @@map("account")\n}\n\nmodel Verification {\n  id         String   @id\n  identifier String\n  value      String\n  expiresAt  DateTime\n  createdAt  DateTime @default(now())\n  updatedAt  DateTime @updatedAt\n\n  @@index([identifier])\n  @@map("verification")\n}\n\nmodel Comment {\n  id   String @id @default(uuid(7))\n  text String\n\n  // For nested comments (replies)\n  parentId String?\n  parent   Comment?  @relation("CommentToComment", fields: [parentId], references: [id], onDelete: Cascade)\n  replies  Comment[] @relation("CommentToComment")\n\n  // Relations to Post and User\n  postId           String\n  userId           String\n  post             Post               @relation(fields: [postId], references: [id], onDelete: Cascade)\n  user             User               @relation(fields: [userId], references: [id], onDelete: Cascade)\n  createdAt        DateTime           @default(now())\n  updatedAt        DateTime           @updatedAt\n  commentReactions CommentReactions[]\n\n  @@index([postId, userId, parentId])\n  @@map("comments")\n}\n\nmodel CommentReactions {\n  id        String       @id @default(uuid(7))\n  type      ReactionType\n  commentId String\n  userId    String\n  comment   Comment      @relation(fields: [commentId], references: [id], onDelete: Cascade)\n  user      User         @relation(fields: [userId], references: [id], onDelete: Cascade)\n  createdAt DateTime     @default(now())\n  updatedAt DateTime     @updatedAt\n\n  @@index([commentId, userId])\n  @@map("comment_reactions")\n}\n\nenum Role {\n  USER\n  ADMIN\n}\n\nenum Privacy {\n  PUBLIC\n  PRIVATE\n}\n\nenum ReactionType {\n  LIKE\n  DISLIKE\n}\n\nmodel Post {\n  id            String          @id @default(uuid(7))\n  text          String?\n  image         String?\n  privacy       Privacy         @default(PUBLIC)\n  // Relations to User\n  userId        String\n  user          User            @relation(fields: [userId], references: [id], onDelete: Cascade)\n  createdAt     DateTime        @default(now())\n  updatedAt     DateTime        @updatedAt\n  comments      Comment[]\n  postReactions PostReactions[]\n\n  @@index([userId])\n  @@map("posts")\n}\n\nmodel PostReactions {\n  id        String       @id @default(uuid())\n  postId    String\n  userId    String\n  reaction  ReactionType\n  createdAt DateTime     @default(now())\n  updatedAt DateTime     @updatedAt\n\n  post Post @relation(fields: [postId], references: [id], onDelete: Cascade)\n  user User @relation(fields: [userId], references: [id], onDelete: Cascade)\n\n  @@unique([userId, postId])\n  @@index([postId, userId])\n  @@map("post_reactions")\n}\n\n// This is your Prisma schema file,\n// learn more about it in the docs: https://pris.ly/d/prisma-schema\n\n// Looking for ways to speed up your queries, or scale easily with your serverless or edge functions?\n// Try Prisma Accelerate: https://pris.ly/cli/accelerate-init\n\ngenerator client {\n  provider = "prisma-client"\n  output   = "../../src/generated/prisma"\n}\n\ndatasource db {\n  provider = "postgresql"\n}\n',
  "runtimeDataModel": {
    "models": {},
    "enums": {},
    "types": {}
  },
  "parameterizationSchema": {
    "strings": [],
    "graph": ""
  }
};
config.runtimeDataModel = JSON.parse('{"models":{"User":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"name","kind":"scalar","type":"String"},{"name":"email","kind":"scalar","type":"String"},{"name":"emailVerified","kind":"scalar","type":"Boolean"},{"name":"image","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"role","kind":"scalar","type":"String"},{"name":"status","kind":"scalar","type":"String"},{"name":"changePassword","kind":"scalar","type":"Boolean"},{"name":"isDeleted","kind":"scalar","type":"Boolean"},{"name":"deletedAt","kind":"scalar","type":"DateTime"},{"name":"sessions","kind":"object","type":"Session","relationName":"SessionToUser"},{"name":"accounts","kind":"object","type":"Account","relationName":"AccountToUser"},{"name":"posts","kind":"object","type":"Post","relationName":"PostToUser"},{"name":"comments","kind":"object","type":"Comment","relationName":"CommentToUser"},{"name":"commentReactions","kind":"object","type":"CommentReactions","relationName":"CommentReactionsToUser"},{"name":"postReactions","kind":"object","type":"PostReactions","relationName":"PostReactionsToUser"}],"dbName":"user"},"Session":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"expiresAt","kind":"scalar","type":"DateTime"},{"name":"token","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"ipAddress","kind":"scalar","type":"String"},{"name":"userAgent","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"user","kind":"object","type":"User","relationName":"SessionToUser"}],"dbName":"session"},"Account":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"accountId","kind":"scalar","type":"String"},{"name":"providerId","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"user","kind":"object","type":"User","relationName":"AccountToUser"},{"name":"accessToken","kind":"scalar","type":"String"},{"name":"refreshToken","kind":"scalar","type":"String"},{"name":"idToken","kind":"scalar","type":"String"},{"name":"accessTokenExpiresAt","kind":"scalar","type":"DateTime"},{"name":"refreshTokenExpiresAt","kind":"scalar","type":"DateTime"},{"name":"scope","kind":"scalar","type":"String"},{"name":"password","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":"account"},"Verification":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"identifier","kind":"scalar","type":"String"},{"name":"value","kind":"scalar","type":"String"},{"name":"expiresAt","kind":"scalar","type":"DateTime"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":"verification"},"Comment":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"text","kind":"scalar","type":"String"},{"name":"parentId","kind":"scalar","type":"String"},{"name":"parent","kind":"object","type":"Comment","relationName":"CommentToComment"},{"name":"replies","kind":"object","type":"Comment","relationName":"CommentToComment"},{"name":"postId","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"post","kind":"object","type":"Post","relationName":"CommentToPost"},{"name":"user","kind":"object","type":"User","relationName":"CommentToUser"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"commentReactions","kind":"object","type":"CommentReactions","relationName":"CommentToCommentReactions"}],"dbName":"comments"},"CommentReactions":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"type","kind":"enum","type":"ReactionType"},{"name":"commentId","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"comment","kind":"object","type":"Comment","relationName":"CommentToCommentReactions"},{"name":"user","kind":"object","type":"User","relationName":"CommentReactionsToUser"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":"comment_reactions"},"Post":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"text","kind":"scalar","type":"String"},{"name":"image","kind":"scalar","type":"String"},{"name":"privacy","kind":"enum","type":"Privacy"},{"name":"userId","kind":"scalar","type":"String"},{"name":"user","kind":"object","type":"User","relationName":"PostToUser"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"comments","kind":"object","type":"Comment","relationName":"CommentToPost"},{"name":"postReactions","kind":"object","type":"PostReactions","relationName":"PostToPostReactions"}],"dbName":"posts"},"PostReactions":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"postId","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"reaction","kind":"enum","type":"ReactionType"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"post","kind":"object","type":"Post","relationName":"PostToPostReactions"},{"name":"user","kind":"object","type":"User","relationName":"PostReactionsToUser"}],"dbName":"post_reactions"}},"enums":{},"types":{}}');
config.parameterizationSchema = {
  strings: JSON.parse('["where","orderBy","cursor","user","sessions","accounts","parent","replies","post","comment","commentReactions","_count","comments","postReactions","posts","User.findUnique","User.findUniqueOrThrow","User.findFirst","User.findFirstOrThrow","User.findMany","data","User.createOne","User.createMany","User.createManyAndReturn","User.updateOne","User.updateMany","User.updateManyAndReturn","create","update","User.upsertOne","User.deleteOne","User.deleteMany","having","_min","_max","User.groupBy","User.aggregate","Session.findUnique","Session.findUniqueOrThrow","Session.findFirst","Session.findFirstOrThrow","Session.findMany","Session.createOne","Session.createMany","Session.createManyAndReturn","Session.updateOne","Session.updateMany","Session.updateManyAndReturn","Session.upsertOne","Session.deleteOne","Session.deleteMany","Session.groupBy","Session.aggregate","Account.findUnique","Account.findUniqueOrThrow","Account.findFirst","Account.findFirstOrThrow","Account.findMany","Account.createOne","Account.createMany","Account.createManyAndReturn","Account.updateOne","Account.updateMany","Account.updateManyAndReturn","Account.upsertOne","Account.deleteOne","Account.deleteMany","Account.groupBy","Account.aggregate","Verification.findUnique","Verification.findUniqueOrThrow","Verification.findFirst","Verification.findFirstOrThrow","Verification.findMany","Verification.createOne","Verification.createMany","Verification.createManyAndReturn","Verification.updateOne","Verification.updateMany","Verification.updateManyAndReturn","Verification.upsertOne","Verification.deleteOne","Verification.deleteMany","Verification.groupBy","Verification.aggregate","Comment.findUnique","Comment.findUniqueOrThrow","Comment.findFirst","Comment.findFirstOrThrow","Comment.findMany","Comment.createOne","Comment.createMany","Comment.createManyAndReturn","Comment.updateOne","Comment.updateMany","Comment.updateManyAndReturn","Comment.upsertOne","Comment.deleteOne","Comment.deleteMany","Comment.groupBy","Comment.aggregate","CommentReactions.findUnique","CommentReactions.findUniqueOrThrow","CommentReactions.findFirst","CommentReactions.findFirstOrThrow","CommentReactions.findMany","CommentReactions.createOne","CommentReactions.createMany","CommentReactions.createManyAndReturn","CommentReactions.updateOne","CommentReactions.updateMany","CommentReactions.updateManyAndReturn","CommentReactions.upsertOne","CommentReactions.deleteOne","CommentReactions.deleteMany","CommentReactions.groupBy","CommentReactions.aggregate","Post.findUnique","Post.findUniqueOrThrow","Post.findFirst","Post.findFirstOrThrow","Post.findMany","Post.createOne","Post.createMany","Post.createManyAndReturn","Post.updateOne","Post.updateMany","Post.updateManyAndReturn","Post.upsertOne","Post.deleteOne","Post.deleteMany","Post.groupBy","Post.aggregate","PostReactions.findUnique","PostReactions.findUniqueOrThrow","PostReactions.findFirst","PostReactions.findFirstOrThrow","PostReactions.findMany","PostReactions.createOne","PostReactions.createMany","PostReactions.createManyAndReturn","PostReactions.updateOne","PostReactions.updateMany","PostReactions.updateManyAndReturn","PostReactions.upsertOne","PostReactions.deleteOne","PostReactions.deleteMany","PostReactions.groupBy","PostReactions.aggregate","AND","OR","NOT","id","postId","userId","ReactionType","reaction","createdAt","updatedAt","equals","in","notIn","lt","lte","gt","gte","not","contains","startsWith","endsWith","text","image","Privacy","privacy","type","commentId","parentId","identifier","value","expiresAt","accountId","providerId","accessToken","refreshToken","idToken","accessTokenExpiresAt","refreshTokenExpiresAt","scope","password","token","ipAddress","userAgent","name","email","emailVerified","role","status","changePassword","isDeleted","deletedAt","every","some","none","userId_postId","is","isNot","connectOrCreate","upsert","createMany","set","disconnect","delete","connect","updateMany","deleteMany"]'),
  graph: "lgREgAEVBAAAigIAIAUAAIsCACAKAACOAgAgDAAAjQIAIA0AAI8CACAOAACMAgAglQEAAIUCADCWAQAAKwAQlwEAAIUCADCYAQEAAAABnQFAAPgBACGeAUAA-AEAIasBAQCHAgAhwAEBAPcBACHBAQEAAAABwgEgAIYCACHDAQEA9wEAIcQBAQD3AQAhxQEgAIYCACHGASAAiAIAIccBQACJAgAhAQAAAAEAIAwDAACUAgAglQEAAJwCADCWAQAAAwAQlwEAAJwCADCYAQEA9wEAIZoBAQD3AQAhnQFAAPgBACGeAUAA-AEAIbMBQAD4AQAhvQEBAPcBACG-AQEAhwIAIb8BAQCHAgAhAwMAANkDACC-AQAApwIAIL8BAACnAgAgDAMAAJQCACCVAQAAnAIAMJYBAAADABCXAQAAnAIAMJgBAQAAAAGaAQEA9wEAIZ0BQAD4AQAhngFAAPgBACGzAUAA-AEAIb0BAQAAAAG-AQEAhwIAIb8BAQCHAgAhAwAAAAMAIAEAAAQAMAIAAAUAIBEDAACUAgAglQEAAJsCADCWAQAABwAQlwEAAJsCADCYAQEA9wEAIZoBAQD3AQAhnQFAAPgBACGeAUAA-AEAIbQBAQD3AQAhtQEBAPcBACG2AQEAhwIAIbcBAQCHAgAhuAEBAIcCACG5AUAAiQIAIboBQACJAgAhuwEBAIcCACG8AQEAhwIAIQgDAADZAwAgtgEAAKcCACC3AQAApwIAILgBAACnAgAguQEAAKcCACC6AQAApwIAILsBAACnAgAgvAEAAKcCACARAwAAlAIAIJUBAACbAgAwlgEAAAcAEJcBAACbAgAwmAEBAAAAAZoBAQD3AQAhnQFAAPgBACGeAUAA-AEAIbQBAQD3AQAhtQEBAPcBACG2AQEAhwIAIbcBAQCHAgAhuAEBAIcCACG5AUAAiQIAIboBQACJAgAhuwEBAIcCACG8AQEAhwIAIQMAAAAHACABAAAIADACAAAJACANAwAAlAIAIAwAAI0CACANAACPAgAglQEAAJkCADCWAQAACwAQlwEAAJkCADCYAQEA9wEAIZoBAQD3AQAhnQFAAPgBACGeAUAA-AEAIaoBAQCHAgAhqwEBAIcCACGtAQAAmgKtASIFAwAA2QMAIAwAANUDACANAADXAwAgqgEAAKcCACCrAQAApwIAIA0DAACUAgAgDAAAjQIAIA0AAI8CACCVAQAAmQIAMJYBAAALABCXAQAAmQIAMJgBAQAAAAGaAQEA9wEAIZ0BQAD4AQAhngFAAPgBACGqAQEAhwIAIasBAQCHAgAhrQEAAJoCrQEiAwAAAAsAIAEAAAwAMAIAAA0AIA8DAACUAgAgBgAAmAIAIAcAAI0CACAIAACTAgAgCgAAjgIAIJUBAACXAgAwlgEAAA8AEJcBAACXAgAwmAEBAPcBACGZAQEA9wEAIZoBAQD3AQAhnQFAAPgBACGeAUAA-AEAIaoBAQD3AQAhsAEBAIcCACEGAwAA2QMAIAYAANoDACAHAADVAwAgCAAA2AMAIAoAANYDACCwAQAApwIAIA8DAACUAgAgBgAAmAIAIAcAAI0CACAIAACTAgAgCgAAjgIAIJUBAACXAgAwlgEAAA8AEJcBAACXAgAwmAEBAAAAAZkBAQD3AQAhmgEBAPcBACGdAUAA-AEAIZ4BQAD4AQAhqgEBAPcBACGwAQEAhwIAIQMAAAAPACABAAAQADACAAARACABAAAADwAgAwAAAA8AIAEAABAAMAIAABEAIAsDAACUAgAgCQAAlgIAIJUBAACVAgAwlgEAABUAEJcBAACVAgAwmAEBAPcBACGaAQEA9wEAIZ0BQAD4AQAhngFAAPgBACGuAQAAkgKcASKvAQEA9wEAIQIDAADZAwAgCQAA2gMAIAsDAACUAgAgCQAAlgIAIJUBAACVAgAwlgEAABUAEJcBAACVAgAwmAEBAAAAAZoBAQD3AQAhnQFAAPgBACGeAUAA-AEAIa4BAACSApwBIq8BAQD3AQAhAwAAABUAIAEAABYAMAIAABcAIAEAAAAPACABAAAAFQAgCwMAAJQCACAIAACTAgAglQEAAJECADCWAQAAGwAQlwEAAJECADCYAQEA9wEAIZkBAQD3AQAhmgEBAPcBACGcAQAAkgKcASKdAUAA-AEAIZ4BQAD4AQAhAgMAANkDACAIAADYAwAgDAMAAJQCACAIAACTAgAglQEAAJECADCWAQAAGwAQlwEAAJECADCYAQEAAAABmQEBAPcBACGaAQEA9wEAIZwBAACSApwBIp0BQAD4AQAhngFAAPgBACHLAQAAkAIAIAMAAAAbACABAAAcADACAAAdACABAAAADwAgAQAAABsAIAMAAAAPACABAAAQADACAAARACADAAAAFQAgAQAAFgAwAgAAFwAgAwAAABsAIAEAABwAMAIAAB0AIAEAAAADACABAAAABwAgAQAAAAsAIAEAAAAPACABAAAAFQAgAQAAABsAIAEAAAABACAVBAAAigIAIAUAAIsCACAKAACOAgAgDAAAjQIAIA0AAI8CACAOAACMAgAglQEAAIUCADCWAQAAKwAQlwEAAIUCADCYAQEA9wEAIZ0BQAD4AQAhngFAAPgBACGrAQEAhwIAIcABAQD3AQAhwQEBAPcBACHCASAAhgIAIcMBAQD3AQAhxAEBAPcBACHFASAAhgIAIcYBIACIAgAhxwFAAIkCACEJBAAA0gMAIAUAANMDACAKAADWAwAgDAAA1QMAIA0AANcDACAOAADUAwAgqwEAAKcCACDGAQAApwIAIMcBAACnAgAgAwAAACsAIAEAACwAMAIAAAEAIAMAAAArACABAAAsADACAAABACADAAAAKwAgAQAALAAwAgAAAQAgEgQAAMwDACAFAADNAwAgCgAA0AMAIAwAAM8DACANAADRAwAgDgAAzgMAIJgBAQAAAAGdAUAAAAABngFAAAAAAasBAQAAAAHAAQEAAAABwQEBAAAAAcIBIAAAAAHDAQEAAAABxAEBAAAAAcUBIAAAAAHGASAAAAABxwFAAAAAAQEUAAAwACAMmAEBAAAAAZ0BQAAAAAGeAUAAAAABqwEBAAAAAcABAQAAAAHBAQEAAAABwgEgAAAAAcMBAQAAAAHEAQEAAAABxQEgAAAAAcYBIAAAAAHHAUAAAAABARQAADIAMAEUAAAyADASBAAAhwMAIAUAAIgDACAKAACLAwAgDAAAigMAIA0AAIwDACAOAACJAwAgmAEBAKACACGdAUAAogIAIZ4BQACiAgAhqwEBAKsCACHAAQEAoAIAIcEBAQCgAgAhwgEgAIUDACHDAQEAoAIAIcQBAQCgAgAhxQEgAIUDACHGASAAhgMAIccBQAD6AgAhAgAAAAEAIBQAADUAIAyYAQEAoAIAIZ0BQACiAgAhngFAAKICACGrAQEAqwIAIcABAQCgAgAhwQEBAKACACHCASAAhQMAIcMBAQCgAgAhxAEBAKACACHFASAAhQMAIcYBIACGAwAhxwFAAPoCACECAAAAKwAgFAAANwAgAgAAACsAIBQAADcAIAMAAAABACAbAAAwACAcAAA1ACABAAAAAQAgAQAAACsAIAYLAACCAwAgIQAAhAMAICIAAIMDACCrAQAApwIAIMYBAACnAgAgxwEAAKcCACAPlQEAAP4BADCWAQAAPgAQlwEAAP4BADCYAQEA4QEAIZ0BQADjAQAhngFAAOMBACGrAQEA7AEAIcABAQDhAQAhwQEBAOEBACHCASAA_wEAIcMBAQDhAQAhxAEBAOEBACHFASAA_wEAIcYBIACAAgAhxwFAAPoBACEDAAAAKwAgAQAAPQAwIAAAPgAgAwAAACsAIAEAACwAMAIAAAEAIAEAAAAFACABAAAABQAgAwAAAAMAIAEAAAQAMAIAAAUAIAMAAAADACABAAAEADACAAAFACADAAAAAwAgAQAABAAwAgAABQAgCQMAAIEDACCYAQEAAAABmgEBAAAAAZ0BQAAAAAGeAUAAAAABswFAAAAAAb0BAQAAAAG-AQEAAAABvwEBAAAAAQEUAABGACAImAEBAAAAAZoBAQAAAAGdAUAAAAABngFAAAAAAbMBQAAAAAG9AQEAAAABvgEBAAAAAb8BAQAAAAEBFAAASAAwARQAAEgAMAkDAACAAwAgmAEBAKACACGaAQEAoAIAIZ0BQACiAgAhngFAAKICACGzAUAAogIAIb0BAQCgAgAhvgEBAKsCACG_AQEAqwIAIQIAAAAFACAUAABLACAImAEBAKACACGaAQEAoAIAIZ0BQACiAgAhngFAAKICACGzAUAAogIAIb0BAQCgAgAhvgEBAKsCACG_AQEAqwIAIQIAAAADACAUAABNACACAAAAAwAgFAAATQAgAwAAAAUAIBsAAEYAIBwAAEsAIAEAAAAFACABAAAAAwAgBQsAAP0CACAhAAD_AgAgIgAA_gIAIL4BAACnAgAgvwEAAKcCACALlQEAAP0BADCWAQAAVAAQlwEAAP0BADCYAQEA4QEAIZoBAQDhAQAhnQFAAOMBACGeAUAA4wEAIbMBQADjAQAhvQEBAOEBACG-AQEA7AEAIb8BAQDsAQAhAwAAAAMAIAEAAFMAMCAAAFQAIAMAAAADACABAAAEADACAAAFACABAAAACQAgAQAAAAkAIAMAAAAHACABAAAIADACAAAJACADAAAABwAgAQAACAAwAgAACQAgAwAAAAcAIAEAAAgAMAIAAAkAIA4DAAD8AgAgmAEBAAAAAZoBAQAAAAGdAUAAAAABngFAAAAAAbQBAQAAAAG1AQEAAAABtgEBAAAAAbcBAQAAAAG4AQEAAAABuQFAAAAAAboBQAAAAAG7AQEAAAABvAEBAAAAAQEUAABcACANmAEBAAAAAZoBAQAAAAGdAUAAAAABngFAAAAAAbQBAQAAAAG1AQEAAAABtgEBAAAAAbcBAQAAAAG4AQEAAAABuQFAAAAAAboBQAAAAAG7AQEAAAABvAEBAAAAAQEUAABeADABFAAAXgAwDgMAAPsCACCYAQEAoAIAIZoBAQCgAgAhnQFAAKICACGeAUAAogIAIbQBAQCgAgAhtQEBAKACACG2AQEAqwIAIbcBAQCrAgAhuAEBAKsCACG5AUAA-gIAIboBQAD6AgAhuwEBAKsCACG8AQEAqwIAIQIAAAAJACAUAABhACANmAEBAKACACGaAQEAoAIAIZ0BQACiAgAhngFAAKICACG0AQEAoAIAIbUBAQCgAgAhtgEBAKsCACG3AQEAqwIAIbgBAQCrAgAhuQFAAPoCACG6AUAA-gIAIbsBAQCrAgAhvAEBAKsCACECAAAABwAgFAAAYwAgAgAAAAcAIBQAAGMAIAMAAAAJACAbAABcACAcAABhACABAAAACQAgAQAAAAcAIAoLAAD3AgAgIQAA-QIAICIAAPgCACC2AQAApwIAILcBAACnAgAguAEAAKcCACC5AQAApwIAILoBAACnAgAguwEAAKcCACC8AQAApwIAIBCVAQAA-QEAMJYBAABqABCXAQAA-QEAMJgBAQDhAQAhmgEBAOEBACGdAUAA4wEAIZ4BQADjAQAhtAEBAOEBACG1AQEA4QEAIbYBAQDsAQAhtwEBAOwBACG4AQEA7AEAIbkBQAD6AQAhugFAAPoBACG7AQEA7AEAIbwBAQDsAQAhAwAAAAcAIAEAAGkAMCAAAGoAIAMAAAAHACABAAAIADACAAAJACAJlQEAAPYBADCWAQAAcAAQlwEAAPYBADCYAQEAAAABnQFAAPgBACGeAUAA-AEAIbEBAQD3AQAhsgEBAPcBACGzAUAA-AEAIQEAAABtACABAAAAbQAgCZUBAAD2AQAwlgEAAHAAEJcBAAD2AQAwmAEBAPcBACGdAUAA-AEAIZ4BQAD4AQAhsQEBAPcBACGyAQEA9wEAIbMBQAD4AQAhAAMAAABwACABAABxADACAABtACADAAAAcAAgAQAAcQAwAgAAbQAgAwAAAHAAIAEAAHEAMAIAAG0AIAaYAQEAAAABnQFAAAAAAZ4BQAAAAAGxAQEAAAABsgEBAAAAAbMBQAAAAAEBFAAAdQAgBpgBAQAAAAGdAUAAAAABngFAAAAAAbEBAQAAAAGyAQEAAAABswFAAAAAAQEUAAB3ADABFAAAdwAwBpgBAQCgAgAhnQFAAKICACGeAUAAogIAIbEBAQCgAgAhsgEBAKACACGzAUAAogIAIQIAAABtACAUAAB6ACAGmAEBAKACACGdAUAAogIAIZ4BQACiAgAhsQEBAKACACGyAQEAoAIAIbMBQACiAgAhAgAAAHAAIBQAAHwAIAIAAABwACAUAAB8ACADAAAAbQAgGwAAdQAgHAAAegAgAQAAAG0AIAEAAABwACADCwAA9AIAICEAAPYCACAiAAD1AgAgCZUBAAD1AQAwlgEAAIMBABCXAQAA9QEAMJgBAQDhAQAhnQFAAOMBACGeAUAA4wEAIbEBAQDhAQAhsgEBAOEBACGzAUAA4wEAIQMAAABwACABAACCAQAwIAAAgwEAIAMAAABwACABAABxADACAABtACABAAAAEQAgAQAAABEAIAMAAAAPACABAAAQADACAAARACADAAAADwAgAQAAEAAwAgAAEQAgAwAAAA8AIAEAABAAMAIAABEAIAwDAADlAgAgBgAA6AIAIAcAAOMCACAIAADkAgAgCgAA5gIAIJgBAQAAAAGZAQEAAAABmgEBAAAAAZ0BQAAAAAGeAUAAAAABqgEBAAAAAbABAQAAAAEBFAAAiwEAIAeYAQEAAAABmQEBAAAAAZoBAQAAAAGdAUAAAAABngFAAAAAAaoBAQAAAAGwAQEAAAABARQAAI0BADABFAAAjQEAMAEAAAAPACAMAwAAyQIAIAYAAMcCACAHAADIAgAgCAAA4QIAIAoAAMoCACCYAQEAoAIAIZkBAQCgAgAhmgEBAKACACGdAUAAogIAIZ4BQACiAgAhqgEBAKACACGwAQEAqwIAIQIAAAARACAUAACRAQAgB5gBAQCgAgAhmQEBAKACACGaAQEAoAIAIZ0BQACiAgAhngFAAKICACGqAQEAoAIAIbABAQCrAgAhAgAAAA8AIBQAAJMBACACAAAADwAgFAAAkwEAIAEAAAAPACADAAAAEQAgGwAAiwEAIBwAAJEBACABAAAAEQAgAQAAAA8AIAQLAADxAgAgIQAA8wIAICIAAPICACCwAQAApwIAIAqVAQAA9AEAMJYBAACbAQAQlwEAAPQBADCYAQEA4QEAIZkBAQDhAQAhmgEBAOEBACGdAUAA4wEAIZ4BQADjAQAhqgEBAOEBACGwAQEA7AEAIQMAAAAPACABAACaAQAwIAAAmwEAIAMAAAAPACABAAAQADACAAARACABAAAAFwAgAQAAABcAIAMAAAAVACABAAAWADACAAAXACADAAAAFQAgAQAAFgAwAgAAFwAgAwAAABUAIAEAABYAMAIAABcAIAgDAADYAgAgCQAA8AIAIJgBAQAAAAGaAQEAAAABnQFAAAAAAZ4BQAAAAAGuAQAAAJwBAq8BAQAAAAEBFAAAowEAIAaYAQEAAAABmgEBAAAAAZ0BQAAAAAGeAUAAAAABrgEAAACcAQKvAQEAAAABARQAAKUBADABFAAApQEAMAgDAADWAgAgCQAA7wIAIJgBAQCgAgAhmgEBAKACACGdAUAAogIAIZ4BQACiAgAhrgEAAKECnAEirwEBAKACACECAAAAFwAgFAAAqAEAIAaYAQEAoAIAIZoBAQCgAgAhnQFAAKICACGeAUAAogIAIa4BAAChApwBIq8BAQCgAgAhAgAAABUAIBQAAKoBACACAAAAFQAgFAAAqgEAIAMAAAAXACAbAACjAQAgHAAAqAEAIAEAAAAXACABAAAAFQAgAwsAAOwCACAhAADuAgAgIgAA7QIAIAmVAQAA8wEAMJYBAACxAQAQlwEAAPMBADCYAQEA4QEAIZoBAQDhAQAhnQFAAOMBACGeAUAA4wEAIa4BAADiAZwBIq8BAQDhAQAhAwAAABUAIAEAALABADAgAACxAQAgAwAAABUAIAEAABYAMAIAABcAIAEAAAANACABAAAADQAgAwAAAAsAIAEAAAwAMAIAAA0AIAMAAAALACABAAAMADACAAANACADAAAACwAgAQAADAAwAgAADQAgCgMAAOkCACAMAADqAgAgDQAA6wIAIJgBAQAAAAGaAQEAAAABnQFAAAAAAZ4BQAAAAAGqAQEAAAABqwEBAAAAAa0BAAAArQECARQAALkBACAHmAEBAAAAAZoBAQAAAAGdAUAAAAABngFAAAAAAaoBAQAAAAGrAQEAAAABrQEAAACtAQIBFAAAuwEAMAEUAAC7AQAwCgMAAK0CACAMAACuAgAgDQAArwIAIJgBAQCgAgAhmgEBAKACACGdAUAAogIAIZ4BQACiAgAhqgEBAKsCACGrAQEAqwIAIa0BAACsAq0BIgIAAAANACAUAAC-AQAgB5gBAQCgAgAhmgEBAKACACGdAUAAogIAIZ4BQACiAgAhqgEBAKsCACGrAQEAqwIAIa0BAACsAq0BIgIAAAALACAUAADAAQAgAgAAAAsAIBQAAMABACADAAAADQAgGwAAuQEAIBwAAL4BACABAAAADQAgAQAAAAsAIAULAACoAgAgIQAAqgIAICIAAKkCACCqAQAApwIAIKsBAACnAgAgCpUBAADrAQAwlgEAAMcBABCXAQAA6wEAMJgBAQDhAQAhmgEBAOEBACGdAUAA4wEAIZ4BQADjAQAhqgEBAOwBACGrAQEA7AEAIa0BAADtAa0BIgMAAAALACABAADGAQAwIAAAxwEAIAMAAAALACABAAAMADACAAANACABAAAAHQAgAQAAAB0AIAMAAAAbACABAAAcADACAAAdACADAAAAGwAgAQAAHAAwAgAAHQAgAwAAABsAIAEAABwAMAIAAB0AIAgDAACmAgAgCAAApQIAIJgBAQAAAAGZAQEAAAABmgEBAAAAAZwBAAAAnAECnQFAAAAAAZ4BQAAAAAEBFAAAzwEAIAaYAQEAAAABmQEBAAAAAZoBAQAAAAGcAQAAAJwBAp0BQAAAAAGeAUAAAAABARQAANEBADABFAAA0QEAMAgDAACkAgAgCAAAowIAIJgBAQCgAgAhmQEBAKACACGaAQEAoAIAIZwBAAChApwBIp0BQACiAgAhngFAAKICACECAAAAHQAgFAAA1AEAIAaYAQEAoAIAIZkBAQCgAgAhmgEBAKACACGcAQAAoQKcASKdAUAAogIAIZ4BQACiAgAhAgAAABsAIBQAANYBACACAAAAGwAgFAAA1gEAIAMAAAAdACAbAADPAQAgHAAA1AEAIAEAAAAdACABAAAAGwAgAwsAAJ0CACAhAACfAgAgIgAAngIAIAmVAQAA4AEAMJYBAADdAQAQlwEAAOABADCYAQEA4QEAIZkBAQDhAQAhmgEBAOEBACGcAQAA4gGcASKdAUAA4wEAIZ4BQADjAQAhAwAAABsAIAEAANwBADAgAADdAQAgAwAAABsAIAEAABwAMAIAAB0AIAmVAQAA4AEAMJYBAADdAQAQlwEAAOABADCYAQEA4QEAIZkBAQDhAQAhmgEBAOEBACGcAQAA4gGcASKdAUAA4wEAIZ4BQADjAQAhDgsAAOUBACAhAADqAQAgIgAA6gEAIJ8BAQAAAAGgAQEAAAAEoQEBAAAABKIBAQAAAAGjAQEAAAABpAEBAAAAAaUBAQAAAAGmAQEA6QEAIacBAQAAAAGoAQEAAAABqQEBAAAAAQcLAADlAQAgIQAA6AEAICIAAOgBACCfAQAAAJwBAqABAAAAnAEIoQEAAACcAQimAQAA5wGcASILCwAA5QEAICEAAOYBACAiAADmAQAgnwFAAAAAAaABQAAAAAShAUAAAAAEogFAAAAAAaMBQAAAAAGkAUAAAAABpQFAAAAAAaYBQADkAQAhCwsAAOUBACAhAADmAQAgIgAA5gEAIJ8BQAAAAAGgAUAAAAAEoQFAAAAABKIBQAAAAAGjAUAAAAABpAFAAAAAAaUBQAAAAAGmAUAA5AEAIQifAQIAAAABoAECAAAABKEBAgAAAASiAQIAAAABowECAAAAAaQBAgAAAAGlAQIAAAABpgECAOUBACEInwFAAAAAAaABQAAAAAShAUAAAAAEogFAAAAAAaMBQAAAAAGkAUAAAAABpQFAAAAAAaYBQADmAQAhBwsAAOUBACAhAADoAQAgIgAA6AEAIJ8BAAAAnAECoAEAAACcAQihAQAAAJwBCKYBAADnAZwBIgSfAQAAAJwBAqABAAAAnAEIoQEAAACcAQimAQAA6AGcASIOCwAA5QEAICEAAOoBACAiAADqAQAgnwEBAAAAAaABAQAAAAShAQEAAAAEogEBAAAAAaMBAQAAAAGkAQEAAAABpQEBAAAAAaYBAQDpAQAhpwEBAAAAAagBAQAAAAGpAQEAAAABC58BAQAAAAGgAQEAAAAEoQEBAAAABKIBAQAAAAGjAQEAAAABpAEBAAAAAaUBAQAAAAGmAQEA6gEAIacBAQAAAAGoAQEAAAABqQEBAAAAAQqVAQAA6wEAMJYBAADHAQAQlwEAAOsBADCYAQEA4QEAIZoBAQDhAQAhnQFAAOMBACGeAUAA4wEAIaoBAQDsAQAhqwEBAOwBACGtAQAA7QGtASIOCwAA8QEAICEAAPIBACAiAADyAQAgnwEBAAAAAaABAQAAAAWhAQEAAAAFogEBAAAAAaMBAQAAAAGkAQEAAAABpQEBAAAAAaYBAQDwAQAhpwEBAAAAAagBAQAAAAGpAQEAAAABBwsAAOUBACAhAADvAQAgIgAA7wEAIJ8BAAAArQECoAEAAACtAQihAQAAAK0BCKYBAADuAa0BIgcLAADlAQAgIQAA7wEAICIAAO8BACCfAQAAAK0BAqABAAAArQEIoQEAAACtAQimAQAA7gGtASIEnwEAAACtAQKgAQAAAK0BCKEBAAAArQEIpgEAAO8BrQEiDgsAAPEBACAhAADyAQAgIgAA8gEAIJ8BAQAAAAGgAQEAAAAFoQEBAAAABaIBAQAAAAGjAQEAAAABpAEBAAAAAaUBAQAAAAGmAQEA8AEAIacBAQAAAAGoAQEAAAABqQEBAAAAAQifAQIAAAABoAECAAAABaEBAgAAAAWiAQIAAAABowECAAAAAaQBAgAAAAGlAQIAAAABpgECAPEBACELnwEBAAAAAaABAQAAAAWhAQEAAAAFogEBAAAAAaMBAQAAAAGkAQEAAAABpQEBAAAAAaYBAQDyAQAhpwEBAAAAAagBAQAAAAGpAQEAAAABCZUBAADzAQAwlgEAALEBABCXAQAA8wEAMJgBAQDhAQAhmgEBAOEBACGdAUAA4wEAIZ4BQADjAQAhrgEAAOIBnAEirwEBAOEBACEKlQEAAPQBADCWAQAAmwEAEJcBAAD0AQAwmAEBAOEBACGZAQEA4QEAIZoBAQDhAQAhnQFAAOMBACGeAUAA4wEAIaoBAQDhAQAhsAEBAOwBACEJlQEAAPUBADCWAQAAgwEAEJcBAAD1AQAwmAEBAOEBACGdAUAA4wEAIZ4BQADjAQAhsQEBAOEBACGyAQEA4QEAIbMBQADjAQAhCZUBAAD2AQAwlgEAAHAAEJcBAAD2AQAwmAEBAPcBACGdAUAA-AEAIZ4BQAD4AQAhsQEBAPcBACGyAQEA9wEAIbMBQAD4AQAhC58BAQAAAAGgAQEAAAAEoQEBAAAABKIBAQAAAAGjAQEAAAABpAEBAAAAAaUBAQAAAAGmAQEA6gEAIacBAQAAAAGoAQEAAAABqQEBAAAAAQifAUAAAAABoAFAAAAABKEBQAAAAASiAUAAAAABowFAAAAAAaQBQAAAAAGlAUAAAAABpgFAAOYBACEQlQEAAPkBADCWAQAAagAQlwEAAPkBADCYAQEA4QEAIZoBAQDhAQAhnQFAAOMBACGeAUAA4wEAIbQBAQDhAQAhtQEBAOEBACG2AQEA7AEAIbcBAQDsAQAhuAEBAOwBACG5AUAA-gEAIboBQAD6AQAhuwEBAOwBACG8AQEA7AEAIQsLAADxAQAgIQAA_AEAICIAAPwBACCfAUAAAAABoAFAAAAABaEBQAAAAAWiAUAAAAABowFAAAAAAaQBQAAAAAGlAUAAAAABpgFAAPsBACELCwAA8QEAICEAAPwBACAiAAD8AQAgnwFAAAAAAaABQAAAAAWhAUAAAAAFogFAAAAAAaMBQAAAAAGkAUAAAAABpQFAAAAAAaYBQAD7AQAhCJ8BQAAAAAGgAUAAAAAFoQFAAAAABaIBQAAAAAGjAUAAAAABpAFAAAAAAaUBQAAAAAGmAUAA_AEAIQuVAQAA_QEAMJYBAABUABCXAQAA_QEAMJgBAQDhAQAhmgEBAOEBACGdAUAA4wEAIZ4BQADjAQAhswFAAOMBACG9AQEA4QEAIb4BAQDsAQAhvwEBAOwBACEPlQEAAP4BADCWAQAAPgAQlwEAAP4BADCYAQEA4QEAIZ0BQADjAQAhngFAAOMBACGrAQEA7AEAIcABAQDhAQAhwQEBAOEBACHCASAA_wEAIcMBAQDhAQAhxAEBAOEBACHFASAA_wEAIcYBIACAAgAhxwFAAPoBACEFCwAA5QEAICEAAIQCACAiAACEAgAgnwEgAAAAAaYBIACDAgAhBQsAAPEBACAhAACCAgAgIgAAggIAIJ8BIAAAAAGmASAAgQIAIQULAADxAQAgIQAAggIAICIAAIICACCfASAAAAABpgEgAIECACECnwEgAAAAAaYBIACCAgAhBQsAAOUBACAhAACEAgAgIgAAhAIAIJ8BIAAAAAGmASAAgwIAIQKfASAAAAABpgEgAIQCACEVBAAAigIAIAUAAIsCACAKAACOAgAgDAAAjQIAIA0AAI8CACAOAACMAgAglQEAAIUCADCWAQAAKwAQlwEAAIUCADCYAQEA9wEAIZ0BQAD4AQAhngFAAPgBACGrAQEAhwIAIcABAQD3AQAhwQEBAPcBACHCASAAhgIAIcMBAQD3AQAhxAEBAPcBACHFASAAhgIAIcYBIACIAgAhxwFAAIkCACECnwEgAAAAAaYBIACEAgAhC58BAQAAAAGgAQEAAAAFoQEBAAAABaIBAQAAAAGjAQEAAAABpAEBAAAAAaUBAQAAAAGmAQEA8gEAIacBAQAAAAGoAQEAAAABqQEBAAAAAQKfASAAAAABpgEgAIICACEInwFAAAAAAaABQAAAAAWhAUAAAAAFogFAAAAAAaMBQAAAAAGkAUAAAAABpQFAAAAAAaYBQAD8AQAhA8gBAAADACDJAQAAAwAgygEAAAMAIAPIAQAABwAgyQEAAAcAIMoBAAAHACADyAEAAAsAIMkBAAALACDKAQAACwAgA8gBAAAPACDJAQAADwAgygEAAA8AIAPIAQAAFQAgyQEAABUAIMoBAAAVACADyAEAABsAIMkBAAAbACDKAQAAGwAgApkBAQAAAAGaAQEAAAABCwMAAJQCACAIAACTAgAglQEAAJECADCWAQAAGwAQlwEAAJECADCYAQEA9wEAIZkBAQD3AQAhmgEBAPcBACGcAQAAkgKcASKdAUAA-AEAIZ4BQAD4AQAhBJ8BAAAAnAECoAEAAACcAQihAQAAAJwBCKYBAADoAZwBIg8DAACUAgAgDAAAjQIAIA0AAI8CACCVAQAAmQIAMJYBAAALABCXAQAAmQIAMJgBAQD3AQAhmgEBAPcBACGdAUAA-AEAIZ4BQAD4AQAhqgEBAIcCACGrAQEAhwIAIa0BAACaAq0BIswBAAALACDNAQAACwAgFwQAAIoCACAFAACLAgAgCgAAjgIAIAwAAI0CACANAACPAgAgDgAAjAIAIJUBAACFAgAwlgEAACsAEJcBAACFAgAwmAEBAPcBACGdAUAA-AEAIZ4BQAD4AQAhqwEBAIcCACHAAQEA9wEAIcEBAQD3AQAhwgEgAIYCACHDAQEA9wEAIcQBAQD3AQAhxQEgAIYCACHGASAAiAIAIccBQACJAgAhzAEAACsAIM0BAAArACALAwAAlAIAIAkAAJYCACCVAQAAlQIAMJYBAAAVABCXAQAAlQIAMJgBAQD3AQAhmgEBAPcBACGdAUAA-AEAIZ4BQAD4AQAhrgEAAJICnAEirwEBAPcBACERAwAAlAIAIAYAAJgCACAHAACNAgAgCAAAkwIAIAoAAI4CACCVAQAAlwIAMJYBAAAPABCXAQAAlwIAMJgBAQD3AQAhmQEBAPcBACGaAQEA9wEAIZ0BQAD4AQAhngFAAPgBACGqAQEA9wEAIbABAQCHAgAhzAEAAA8AIM0BAAAPACAPAwAAlAIAIAYAAJgCACAHAACNAgAgCAAAkwIAIAoAAI4CACCVAQAAlwIAMJYBAAAPABCXAQAAlwIAMJgBAQD3AQAhmQEBAPcBACGaAQEA9wEAIZ0BQAD4AQAhngFAAPgBACGqAQEA9wEAIbABAQCHAgAhEQMAAJQCACAGAACYAgAgBwAAjQIAIAgAAJMCACAKAACOAgAglQEAAJcCADCWAQAADwAQlwEAAJcCADCYAQEA9wEAIZkBAQD3AQAhmgEBAPcBACGdAUAA-AEAIZ4BQAD4AQAhqgEBAPcBACGwAQEAhwIAIcwBAAAPACDNAQAADwAgDQMAAJQCACAMAACNAgAgDQAAjwIAIJUBAACZAgAwlgEAAAsAEJcBAACZAgAwmAEBAPcBACGaAQEA9wEAIZ0BQAD4AQAhngFAAPgBACGqAQEAhwIAIasBAQCHAgAhrQEAAJoCrQEiBJ8BAAAArQECoAEAAACtAQihAQAAAK0BCKYBAADvAa0BIhEDAACUAgAglQEAAJsCADCWAQAABwAQlwEAAJsCADCYAQEA9wEAIZoBAQD3AQAhnQFAAPgBACGeAUAA-AEAIbQBAQD3AQAhtQEBAPcBACG2AQEAhwIAIbcBAQCHAgAhuAEBAIcCACG5AUAAiQIAIboBQACJAgAhuwEBAIcCACG8AQEAhwIAIQwDAACUAgAglQEAAJwCADCWAQAAAwAQlwEAAJwCADCYAQEA9wEAIZoBAQD3AQAhnQFAAPgBACGeAUAA-AEAIbMBQAD4AQAhvQEBAPcBACG-AQEAhwIAIb8BAQCHAgAhAAAAAdEBAQAAAAEB0QEAAACcAQIB0QFAAAAAAQUbAACPBAAgHAAAlQQAIM4BAACQBAAgzwEAAJQEACDUAQAADQAgBRsAAI0EACAcAACSBAAgzgEAAI4EACDPAQAAkQQAINQBAAABACADGwAAjwQAIM4BAACQBAAg1AEAAA0AIAMbAACNBAAgzgEAAI4EACDUAQAAAQAgAAAAAAHRAQEAAAABAdEBAAAArQECBRsAAPADACAcAACLBAAgzgEAAPEDACDPAQAAigQAINQBAAABACALGwAAvAIAMBwAAMECADDOAQAAvQIAMM8BAAC-AgAw0AEAAL8CACDRAQAAwAIAMNIBAADAAgAw0wEAAMACADDUAQAAwAIAMNUBAADCAgAw1gEAAMMCADALGwAAsAIAMBwAALUCADDOAQAAsQIAMM8BAACyAgAw0AEAALMCACDRAQAAtAIAMNIBAAC0AgAw0wEAALQCADDUAQAAtAIAMNUBAAC2AgAw1gEAALcCADAGAwAApgIAIJgBAQAAAAGaAQEAAAABnAEAAACcAQKdAUAAAAABngFAAAAAAQIAAAAdACAbAAC7AgAgAwAAAB0AIBsAALsCACAcAAC6AgAgARQAAIkEADAMAwAAlAIAIAgAAJMCACCVAQAAkQIAMJYBAAAbABCXAQAAkQIAMJgBAQAAAAGZAQEA9wEAIZoBAQD3AQAhnAEAAJICnAEinQFAAPgBACGeAUAA-AEAIcsBAACQAgAgAgAAAB0AIBQAALoCACACAAAAuAIAIBQAALkCACAJlQEAALcCADCWAQAAuAIAEJcBAAC3AgAwmAEBAPcBACGZAQEA9wEAIZoBAQD3AQAhnAEAAJICnAEinQFAAPgBACGeAUAA-AEAIQmVAQAAtwIAMJYBAAC4AgAQlwEAALcCADCYAQEA9wEAIZkBAQD3AQAhmgEBAPcBACGcAQAAkgKcASKdAUAA-AEAIZ4BQAD4AQAhBZgBAQCgAgAhmgEBAKACACGcAQAAoQKcASKdAUAAogIAIZ4BQACiAgAhBgMAAKQCACCYAQEAoAIAIZoBAQCgAgAhnAEAAKECnAEinQFAAKICACGeAUAAogIAIQYDAACmAgAgmAEBAAAAAZoBAQAAAAGcAQAAAJwBAp0BQAAAAAGeAUAAAAABCgMAAOUCACAGAADoAgAgBwAA4wIAIAoAAOYCACCYAQEAAAABmgEBAAAAAZ0BQAAAAAGeAUAAAAABqgEBAAAAAbABAQAAAAECAAAAEQAgGwAA5wIAIAMAAAARACAbAADnAgAgHAAAxgIAIAEUAACIBAAwDwMAAJQCACAGAACYAgAgBwAAjQIAIAgAAJMCACAKAACOAgAglQEAAJcCADCWAQAADwAQlwEAAJcCADCYAQEAAAABmQEBAPcBACGaAQEA9wEAIZ0BQAD4AQAhngFAAPgBACGqAQEA9wEAIbABAQCHAgAhAgAAABEAIBQAAMYCACACAAAAxAIAIBQAAMUCACAKlQEAAMMCADCWAQAAxAIAEJcBAADDAgAwmAEBAPcBACGZAQEA9wEAIZoBAQD3AQAhnQFAAPgBACGeAUAA-AEAIaoBAQD3AQAhsAEBAIcCACEKlQEAAMMCADCWAQAAxAIAEJcBAADDAgAwmAEBAPcBACGZAQEA9wEAIZoBAQD3AQAhnQFAAPgBACGeAUAA-AEAIaoBAQD3AQAhsAEBAIcCACEGmAEBAKACACGaAQEAoAIAIZ0BQACiAgAhngFAAKICACGqAQEAoAIAIbABAQCrAgAhCgMAAMkCACAGAADHAgAgBwAAyAIAIAoAAMoCACCYAQEAoAIAIZoBAQCgAgAhnQFAAKICACGeAUAAogIAIaoBAQCgAgAhsAEBAKsCACEHGwAA8gMAIBwAAIYEACDOAQAA8wMAIM8BAACFBAAg0gEAAA8AINMBAAAPACDUAQAAEQAgCxsAANkCADAcAADdAgAwzgEAANoCADDPAQAA2wIAMNABAADcAgAg0QEAAMACADDSAQAAwAIAMNMBAADAAgAw1AEAAMACADDVAQAA3gIAMNYBAADDAgAwBRsAAPQDACAcAACDBAAgzgEAAPUDACDPAQAAggQAINQBAAABACALGwAAywIAMBwAANACADDOAQAAzAIAMM8BAADNAgAw0AEAAM4CACDRAQAAzwIAMNIBAADPAgAw0wEAAM8CADDUAQAAzwIAMNUBAADRAgAw1gEAANICADAGAwAA2AIAIJgBAQAAAAGaAQEAAAABnQFAAAAAAZ4BQAAAAAGuAQAAAJwBAgIAAAAXACAbAADXAgAgAwAAABcAIBsAANcCACAcAADVAgAgARQAAIEEADALAwAAlAIAIAkAAJYCACCVAQAAlQIAMJYBAAAVABCXAQAAlQIAMJgBAQAAAAGaAQEA9wEAIZ0BQAD4AQAhngFAAPgBACGuAQAAkgKcASKvAQEA9wEAIQIAAAAXACAUAADVAgAgAgAAANMCACAUAADUAgAgCZUBAADSAgAwlgEAANMCABCXAQAA0gIAMJgBAQD3AQAhmgEBAPcBACGdAUAA-AEAIZ4BQAD4AQAhrgEAAJICnAEirwEBAPcBACEJlQEAANICADCWAQAA0wIAEJcBAADSAgAwmAEBAPcBACGaAQEA9wEAIZ0BQAD4AQAhngFAAPgBACGuAQAAkgKcASKvAQEA9wEAIQWYAQEAoAIAIZoBAQCgAgAhnQFAAKICACGeAUAAogIAIa4BAAChApwBIgYDAADWAgAgmAEBAKACACGaAQEAoAIAIZ0BQACiAgAhngFAAKICACGuAQAAoQKcASIFGwAA_AMAIBwAAP8DACDOAQAA_QMAIM8BAAD-AwAg1AEAAAEAIAYDAADYAgAgmAEBAAAAAZoBAQAAAAGdAUAAAAABngFAAAAAAa4BAAAAnAECAxsAAPwDACDOAQAA_QMAINQBAAABACAKAwAA5QIAIAcAAOMCACAIAADkAgAgCgAA5gIAIJgBAQAAAAGZAQEAAAABmgEBAAAAAZ0BQAAAAAGeAUAAAAABqgEBAAAAAQIAAAARACAbAADiAgAgAwAAABEAIBsAAOICACAcAADgAgAgARQAAPsDADACAAAAEQAgFAAA4AIAIAIAAADEAgAgFAAA3wIAIAaYAQEAoAIAIZkBAQCgAgAhmgEBAKACACGdAUAAogIAIZ4BQACiAgAhqgEBAKACACEKAwAAyQIAIAcAAMgCACAIAADhAgAgCgAAygIAIJgBAQCgAgAhmQEBAKACACGaAQEAoAIAIZ0BQACiAgAhngFAAKICACGqAQEAoAIAIQUbAAD2AwAgHAAA-QMAIM4BAAD3AwAgzwEAAPgDACDUAQAADQAgCgMAAOUCACAHAADjAgAgCAAA5AIAIAoAAOYCACCYAQEAAAABmQEBAAAAAZoBAQAAAAGdAUAAAAABngFAAAAAAaoBAQAAAAEEGwAA2QIAMM4BAADaAgAw0AEAANwCACDUAQAAwAIAMAMbAAD2AwAgzgEAAPcDACDUAQAADQAgAxsAAPQDACDOAQAA9QMAINQBAAABACAEGwAAywIAMM4BAADMAgAw0AEAAM4CACDUAQAAzwIAMAoDAADlAgAgBgAA6AIAIAcAAOMCACAKAADmAgAgmAEBAAAAAZoBAQAAAAGdAUAAAAABngFAAAAAAaoBAQAAAAGwAQEAAAABAxsAAPIDACDOAQAA8wMAINQBAAARACADGwAA8AMAIM4BAADxAwAg1AEAAAEAIAQbAAC8AgAwzgEAAL0CADDQAQAAvwIAINQBAADAAgAwBBsAALACADDOAQAAsQIAMNABAACzAgAg1AEAALQCADAAAAAFGwAA6wMAIBwAAO4DACDOAQAA7AMAIM8BAADtAwAg1AEAABEAIAMbAADrAwAgzgEAAOwDACDUAQAAEQAgAAAAAAAAAAAAAdEBQAAAAAEFGwAA5gMAIBwAAOkDACDOAQAA5wMAIM8BAADoAwAg1AEAAAEAIAMbAADmAwAgzgEAAOcDACDUAQAAAQAgAAAABRsAAOEDACAcAADkAwAgzgEAAOIDACDPAQAA4wMAINQBAAABACADGwAA4QMAIM4BAADiAwAg1AEAAAEAIAAAAAHRASAAAAABAdEBIAAAAAELGwAAwAMAMBwAAMUDADDOAQAAwQMAMM8BAADCAwAw0AEAAMMDACDRAQAAxAMAMNIBAADEAwAw0wEAAMQDADDUAQAAxAMAMNUBAADGAwAw1gEAAMcDADALGwAAtAMAMBwAALkDADDOAQAAtQMAMM8BAAC2AwAw0AEAALcDACDRAQAAuAMAMNIBAAC4AwAw0wEAALgDADDUAQAAuAMAMNUBAAC6AwAw1gEAALsDADALGwAAqAMAMBwAAK0DADDOAQAAqQMAMM8BAACqAwAw0AEAAKsDACDRAQAArAMAMNIBAACsAwAw0wEAAKwDADDUAQAArAMAMNUBAACuAwAw1gEAAK8DADALGwAAnwMAMBwAAKMDADDOAQAAoAMAMM8BAAChAwAw0AEAAKIDACDRAQAAwAIAMNIBAADAAgAw0wEAAMACADDUAQAAwAIAMNUBAACkAwAw1gEAAMMCADALGwAAlgMAMBwAAJoDADDOAQAAlwMAMM8BAACYAwAw0AEAAJkDACDRAQAAzwIAMNIBAADPAgAw0wEAAM8CADDUAQAAzwIAMNUBAACbAwAw1gEAANICADALGwAAjQMAMBwAAJEDADDOAQAAjgMAMM8BAACPAwAw0AEAAJADACDRAQAAtAIAMNIBAAC0AgAw0wEAALQCADDUAQAAtAIAMNUBAACSAwAw1gEAALcCADAGCAAApQIAIJgBAQAAAAGZAQEAAAABnAEAAACcAQKdAUAAAAABngFAAAAAAQIAAAAdACAbAACVAwAgAwAAAB0AIBsAAJUDACAcAACUAwAgARQAAOADADACAAAAHQAgFAAAlAMAIAIAAAC4AgAgFAAAkwMAIAWYAQEAoAIAIZkBAQCgAgAhnAEAAKECnAEinQFAAKICACGeAUAAogIAIQYIAACjAgAgmAEBAKACACGZAQEAoAIAIZwBAAChApwBIp0BQACiAgAhngFAAKICACEGCAAApQIAIJgBAQAAAAGZAQEAAAABnAEAAACcAQKdAUAAAAABngFAAAAAAQYJAADwAgAgmAEBAAAAAZ0BQAAAAAGeAUAAAAABrgEAAACcAQKvAQEAAAABAgAAABcAIBsAAJ4DACADAAAAFwAgGwAAngMAIBwAAJ0DACABFAAA3wMAMAIAAAAXACAUAACdAwAgAgAAANMCACAUAACcAwAgBZgBAQCgAgAhnQFAAKICACGeAUAAogIAIa4BAAChApwBIq8BAQCgAgAhBgkAAO8CACCYAQEAoAIAIZ0BQACiAgAhngFAAKICACGuAQAAoQKcASKvAQEAoAIAIQYJAADwAgAgmAEBAAAAAZ0BQAAAAAGeAUAAAAABrgEAAACcAQKvAQEAAAABCgYAAOgCACAHAADjAgAgCAAA5AIAIAoAAOYCACCYAQEAAAABmQEBAAAAAZ0BQAAAAAGeAUAAAAABqgEBAAAAAbABAQAAAAECAAAAEQAgGwAApwMAIAMAAAARACAbAACnAwAgHAAApgMAIAEUAADeAwAwAgAAABEAIBQAAKYDACACAAAAxAIAIBQAAKUDACAGmAEBAKACACGZAQEAoAIAIZ0BQACiAgAhngFAAKICACGqAQEAoAIAIbABAQCrAgAhCgYAAMcCACAHAADIAgAgCAAA4QIAIAoAAMoCACCYAQEAoAIAIZkBAQCgAgAhnQFAAKICACGeAUAAogIAIaoBAQCgAgAhsAEBAKsCACEKBgAA6AIAIAcAAOMCACAIAADkAgAgCgAA5gIAIJgBAQAAAAGZAQEAAAABnQFAAAAAAZ4BQAAAAAGqAQEAAAABsAEBAAAAAQgMAADqAgAgDQAA6wIAIJgBAQAAAAGdAUAAAAABngFAAAAAAaoBAQAAAAGrAQEAAAABrQEAAACtAQICAAAADQAgGwAAswMAIAMAAAANACAbAACzAwAgHAAAsgMAIAEUAADdAwAwDQMAAJQCACAMAACNAgAgDQAAjwIAIJUBAACZAgAwlgEAAAsAEJcBAACZAgAwmAEBAAAAAZoBAQD3AQAhnQFAAPgBACGeAUAA-AEAIaoBAQCHAgAhqwEBAIcCACGtAQAAmgKtASICAAAADQAgFAAAsgMAIAIAAACwAwAgFAAAsQMAIAqVAQAArwMAMJYBAACwAwAQlwEAAK8DADCYAQEA9wEAIZoBAQD3AQAhnQFAAPgBACGeAUAA-AEAIaoBAQCHAgAhqwEBAIcCACGtAQAAmgKtASIKlQEAAK8DADCWAQAAsAMAEJcBAACvAwAwmAEBAPcBACGaAQEA9wEAIZ0BQAD4AQAhngFAAPgBACGqAQEAhwIAIasBAQCHAgAhrQEAAJoCrQEiBpgBAQCgAgAhnQFAAKICACGeAUAAogIAIaoBAQCrAgAhqwEBAKsCACGtAQAArAKtASIIDAAArgIAIA0AAK8CACCYAQEAoAIAIZ0BQACiAgAhngFAAKICACGqAQEAqwIAIasBAQCrAgAhrQEAAKwCrQEiCAwAAOoCACANAADrAgAgmAEBAAAAAZ0BQAAAAAGeAUAAAAABqgEBAAAAAasBAQAAAAGtAQAAAK0BAgyYAQEAAAABnQFAAAAAAZ4BQAAAAAG0AQEAAAABtQEBAAAAAbYBAQAAAAG3AQEAAAABuAEBAAAAAbkBQAAAAAG6AUAAAAABuwEBAAAAAbwBAQAAAAECAAAACQAgGwAAvwMAIAMAAAAJACAbAAC_AwAgHAAAvgMAIAEUAADcAwAwEQMAAJQCACCVAQAAmwIAMJYBAAAHABCXAQAAmwIAMJgBAQAAAAGaAQEA9wEAIZ0BQAD4AQAhngFAAPgBACG0AQEA9wEAIbUBAQD3AQAhtgEBAIcCACG3AQEAhwIAIbgBAQCHAgAhuQFAAIkCACG6AUAAiQIAIbsBAQCHAgAhvAEBAIcCACECAAAACQAgFAAAvgMAIAIAAAC8AwAgFAAAvQMAIBCVAQAAuwMAMJYBAAC8AwAQlwEAALsDADCYAQEA9wEAIZoBAQD3AQAhnQFAAPgBACGeAUAA-AEAIbQBAQD3AQAhtQEBAPcBACG2AQEAhwIAIbcBAQCHAgAhuAEBAIcCACG5AUAAiQIAIboBQACJAgAhuwEBAIcCACG8AQEAhwIAIRCVAQAAuwMAMJYBAAC8AwAQlwEAALsDADCYAQEA9wEAIZoBAQD3AQAhnQFAAPgBACGeAUAA-AEAIbQBAQD3AQAhtQEBAPcBACG2AQEAhwIAIbcBAQCHAgAhuAEBAIcCACG5AUAAiQIAIboBQACJAgAhuwEBAIcCACG8AQEAhwIAIQyYAQEAoAIAIZ0BQACiAgAhngFAAKICACG0AQEAoAIAIbUBAQCgAgAhtgEBAKsCACG3AQEAqwIAIbgBAQCrAgAhuQFAAPoCACG6AUAA-gIAIbsBAQCrAgAhvAEBAKsCACEMmAEBAKACACGdAUAAogIAIZ4BQACiAgAhtAEBAKACACG1AQEAoAIAIbYBAQCrAgAhtwEBAKsCACG4AQEAqwIAIbkBQAD6AgAhugFAAPoCACG7AQEAqwIAIbwBAQCrAgAhDJgBAQAAAAGdAUAAAAABngFAAAAAAbQBAQAAAAG1AQEAAAABtgEBAAAAAbcBAQAAAAG4AQEAAAABuQFAAAAAAboBQAAAAAG7AQEAAAABvAEBAAAAAQeYAQEAAAABnQFAAAAAAZ4BQAAAAAGzAUAAAAABvQEBAAAAAb4BAQAAAAG_AQEAAAABAgAAAAUAIBsAAMsDACADAAAABQAgGwAAywMAIBwAAMoDACABFAAA2wMAMAwDAACUAgAglQEAAJwCADCWAQAAAwAQlwEAAJwCADCYAQEAAAABmgEBAPcBACGdAUAA-AEAIZ4BQAD4AQAhswFAAPgBACG9AQEAAAABvgEBAIcCACG_AQEAhwIAIQIAAAAFACAUAADKAwAgAgAAAMgDACAUAADJAwAgC5UBAADHAwAwlgEAAMgDABCXAQAAxwMAMJgBAQD3AQAhmgEBAPcBACGdAUAA-AEAIZ4BQAD4AQAhswFAAPgBACG9AQEA9wEAIb4BAQCHAgAhvwEBAIcCACELlQEAAMcDADCWAQAAyAMAEJcBAADHAwAwmAEBAPcBACGaAQEA9wEAIZ0BQAD4AQAhngFAAPgBACGzAUAA-AEAIb0BAQD3AQAhvgEBAIcCACG_AQEAhwIAIQeYAQEAoAIAIZ0BQACiAgAhngFAAKICACGzAUAAogIAIb0BAQCgAgAhvgEBAKsCACG_AQEAqwIAIQeYAQEAoAIAIZ0BQACiAgAhngFAAKICACGzAUAAogIAIb0BAQCgAgAhvgEBAKsCACG_AQEAqwIAIQeYAQEAAAABnQFAAAAAAZ4BQAAAAAGzAUAAAAABvQEBAAAAAb4BAQAAAAG_AQEAAAABBBsAAMADADDOAQAAwQMAMNABAADDAwAg1AEAAMQDADAEGwAAtAMAMM4BAAC1AwAw0AEAALcDACDUAQAAuAMAMAQbAACoAwAwzgEAAKkDADDQAQAAqwMAINQBAACsAwAwBBsAAJ8DADDOAQAAoAMAMNABAACiAwAg1AEAAMACADAEGwAAlgMAMM4BAACXAwAw0AEAAJkDACDUAQAAzwIAMAQbAACNAwAwzgEAAI4DADDQAQAAkAMAINQBAAC0AgAwAAAAAAAABQMAANkDACAMAADVAwAgDQAA1wMAIKoBAACnAgAgqwEAAKcCACAJBAAA0gMAIAUAANMDACAKAADWAwAgDAAA1QMAIA0AANcDACAOAADUAwAgqwEAAKcCACDGAQAApwIAIMcBAACnAgAgBgMAANkDACAGAADaAwAgBwAA1QMAIAgAANgDACAKAADWAwAgsAEAAKcCACAHmAEBAAAAAZ0BQAAAAAGeAUAAAAABswFAAAAAAb0BAQAAAAG-AQEAAAABvwEBAAAAAQyYAQEAAAABnQFAAAAAAZ4BQAAAAAG0AQEAAAABtQEBAAAAAbYBAQAAAAG3AQEAAAABuAEBAAAAAbkBQAAAAAG6AUAAAAABuwEBAAAAAbwBAQAAAAEGmAEBAAAAAZ0BQAAAAAGeAUAAAAABqgEBAAAAAasBAQAAAAGtAQAAAK0BAgaYAQEAAAABmQEBAAAAAZ0BQAAAAAGeAUAAAAABqgEBAAAAAbABAQAAAAEFmAEBAAAAAZ0BQAAAAAGeAUAAAAABrgEAAACcAQKvAQEAAAABBZgBAQAAAAGZAQEAAAABnAEAAACcAQKdAUAAAAABngFAAAAAAREFAADNAwAgCgAA0AMAIAwAAM8DACANAADRAwAgDgAAzgMAIJgBAQAAAAGdAUAAAAABngFAAAAAAasBAQAAAAHAAQEAAAABwQEBAAAAAcIBIAAAAAHDAQEAAAABxAEBAAAAAcUBIAAAAAHGASAAAAABxwFAAAAAAQIAAAABACAbAADhAwAgAwAAACsAIBsAAOEDACAcAADlAwAgEwAAACsAIAUAAIgDACAKAACLAwAgDAAAigMAIA0AAIwDACAOAACJAwAgFAAA5QMAIJgBAQCgAgAhnQFAAKICACGeAUAAogIAIasBAQCrAgAhwAEBAKACACHBAQEAoAIAIcIBIACFAwAhwwEBAKACACHEAQEAoAIAIcUBIACFAwAhxgEgAIYDACHHAUAA-gIAIREFAACIAwAgCgAAiwMAIAwAAIoDACANAACMAwAgDgAAiQMAIJgBAQCgAgAhnQFAAKICACGeAUAAogIAIasBAQCrAgAhwAEBAKACACHBAQEAoAIAIcIBIACFAwAhwwEBAKACACHEAQEAoAIAIcUBIACFAwAhxgEgAIYDACHHAUAA-gIAIREEAADMAwAgCgAA0AMAIAwAAM8DACANAADRAwAgDgAAzgMAIJgBAQAAAAGdAUAAAAABngFAAAAAAasBAQAAAAHAAQEAAAABwQEBAAAAAcIBIAAAAAHDAQEAAAABxAEBAAAAAcUBIAAAAAHGASAAAAABxwFAAAAAAQIAAAABACAbAADmAwAgAwAAACsAIBsAAOYDACAcAADqAwAgEwAAACsAIAQAAIcDACAKAACLAwAgDAAAigMAIA0AAIwDACAOAACJAwAgFAAA6gMAIJgBAQCgAgAhnQFAAKICACGeAUAAogIAIasBAQCrAgAhwAEBAKACACHBAQEAoAIAIcIBIACFAwAhwwEBAKACACHEAQEAoAIAIcUBIACFAwAhxgEgAIYDACHHAUAA-gIAIREEAACHAwAgCgAAiwMAIAwAAIoDACANAACMAwAgDgAAiQMAIJgBAQCgAgAhnQFAAKICACGeAUAAogIAIasBAQCrAgAhwAEBAKACACHBAQEAoAIAIcIBIACFAwAhwwEBAKACACHEAQEAoAIAIcUBIACFAwAhxgEgAIYDACHHAUAA-gIAIQsDAADlAgAgBgAA6AIAIAcAAOMCACAIAADkAgAgmAEBAAAAAZkBAQAAAAGaAQEAAAABnQFAAAAAAZ4BQAAAAAGqAQEAAAABsAEBAAAAAQIAAAARACAbAADrAwAgAwAAAA8AIBsAAOsDACAcAADvAwAgDQAAAA8AIAMAAMkCACAGAADHAgAgBwAAyAIAIAgAAOECACAUAADvAwAgmAEBAKACACGZAQEAoAIAIZoBAQCgAgAhnQFAAKICACGeAUAAogIAIaoBAQCgAgAhsAEBAKsCACELAwAAyQIAIAYAAMcCACAHAADIAgAgCAAA4QIAIJgBAQCgAgAhmQEBAKACACGaAQEAoAIAIZ0BQACiAgAhngFAAKICACGqAQEAoAIAIbABAQCrAgAhEQQAAMwDACAFAADNAwAgCgAA0AMAIAwAAM8DACANAADRAwAgmAEBAAAAAZ0BQAAAAAGeAUAAAAABqwEBAAAAAcABAQAAAAHBAQEAAAABwgEgAAAAAcMBAQAAAAHEAQEAAAABxQEgAAAAAcYBIAAAAAHHAUAAAAABAgAAAAEAIBsAAPADACALAwAA5QIAIAYAAOgCACAIAADkAgAgCgAA5gIAIJgBAQAAAAGZAQEAAAABmgEBAAAAAZ0BQAAAAAGeAUAAAAABqgEBAAAAAbABAQAAAAECAAAAEQAgGwAA8gMAIBEEAADMAwAgBQAAzQMAIAoAANADACANAADRAwAgDgAAzgMAIJgBAQAAAAGdAUAAAAABngFAAAAAAasBAQAAAAHAAQEAAAABwQEBAAAAAcIBIAAAAAHDAQEAAAABxAEBAAAAAcUBIAAAAAHGASAAAAABxwFAAAAAAQIAAAABACAbAAD0AwAgCQMAAOkCACANAADrAgAgmAEBAAAAAZoBAQAAAAGdAUAAAAABngFAAAAAAaoBAQAAAAGrAQEAAAABrQEAAACtAQICAAAADQAgGwAA9gMAIAMAAAALACAbAAD2AwAgHAAA-gMAIAsAAAALACADAACtAgAgDQAArwIAIBQAAPoDACCYAQEAoAIAIZoBAQCgAgAhnQFAAKICACGeAUAAogIAIaoBAQCrAgAhqwEBAKsCACGtAQAArAKtASIJAwAArQIAIA0AAK8CACCYAQEAoAIAIZoBAQCgAgAhnQFAAKICACGeAUAAogIAIaoBAQCrAgAhqwEBAKsCACGtAQAArAKtASIGmAEBAAAAAZkBAQAAAAGaAQEAAAABnQFAAAAAAZ4BQAAAAAGqAQEAAAABEQQAAMwDACAFAADNAwAgDAAAzwMAIA0AANEDACAOAADOAwAgmAEBAAAAAZ0BQAAAAAGeAUAAAAABqwEBAAAAAcABAQAAAAHBAQEAAAABwgEgAAAAAcMBAQAAAAHEAQEAAAABxQEgAAAAAcYBIAAAAAHHAUAAAAABAgAAAAEAIBsAAPwDACADAAAAKwAgGwAA_AMAIBwAAIAEACATAAAAKwAgBAAAhwMAIAUAAIgDACAMAACKAwAgDQAAjAMAIA4AAIkDACAUAACABAAgmAEBAKACACGdAUAAogIAIZ4BQACiAgAhqwEBAKsCACHAAQEAoAIAIcEBAQCgAgAhwgEgAIUDACHDAQEAoAIAIcQBAQCgAgAhxQEgAIUDACHGASAAhgMAIccBQAD6AgAhEQQAAIcDACAFAACIAwAgDAAAigMAIA0AAIwDACAOAACJAwAgmAEBAKACACGdAUAAogIAIZ4BQACiAgAhqwEBAKsCACHAAQEAoAIAIcEBAQCgAgAhwgEgAIUDACHDAQEAoAIAIcQBAQCgAgAhxQEgAIUDACHGASAAhgMAIccBQAD6AgAhBZgBAQAAAAGaAQEAAAABnQFAAAAAAZ4BQAAAAAGuAQAAAJwBAgMAAAArACAbAAD0AwAgHAAAhAQAIBMAAAArACAEAACHAwAgBQAAiAMAIAoAAIsDACANAACMAwAgDgAAiQMAIBQAAIQEACCYAQEAoAIAIZ0BQACiAgAhngFAAKICACGrAQEAqwIAIcABAQCgAgAhwQEBAKACACHCASAAhQMAIcMBAQCgAgAhxAEBAKACACHFASAAhQMAIcYBIACGAwAhxwFAAPoCACERBAAAhwMAIAUAAIgDACAKAACLAwAgDQAAjAMAIA4AAIkDACCYAQEAoAIAIZ0BQACiAgAhngFAAKICACGrAQEAqwIAIcABAQCgAgAhwQEBAKACACHCASAAhQMAIcMBAQCgAgAhxAEBAKACACHFASAAhQMAIcYBIACGAwAhxwFAAPoCACEDAAAADwAgGwAA8gMAIBwAAIcEACANAAAADwAgAwAAyQIAIAYAAMcCACAIAADhAgAgCgAAygIAIBQAAIcEACCYAQEAoAIAIZkBAQCgAgAhmgEBAKACACGdAUAAogIAIZ4BQACiAgAhqgEBAKACACGwAQEAqwIAIQsDAADJAgAgBgAAxwIAIAgAAOECACAKAADKAgAgmAEBAKACACGZAQEAoAIAIZoBAQCgAgAhnQFAAKICACGeAUAAogIAIaoBAQCgAgAhsAEBAKsCACEGmAEBAAAAAZoBAQAAAAGdAUAAAAABngFAAAAAAaoBAQAAAAGwAQEAAAABBZgBAQAAAAGaAQEAAAABnAEAAACcAQKdAUAAAAABngFAAAAAAQMAAAArACAbAADwAwAgHAAAjAQAIBMAAAArACAEAACHAwAgBQAAiAMAIAoAAIsDACAMAACKAwAgDQAAjAMAIBQAAIwEACCYAQEAoAIAIZ0BQACiAgAhngFAAKICACGrAQEAqwIAIcABAQCgAgAhwQEBAKACACHCASAAhQMAIcMBAQCgAgAhxAEBAKACACHFASAAhQMAIcYBIACGAwAhxwFAAPoCACERBAAAhwMAIAUAAIgDACAKAACLAwAgDAAAigMAIA0AAIwDACCYAQEAoAIAIZ0BQACiAgAhngFAAKICACGrAQEAqwIAIcABAQCgAgAhwQEBAKACACHCASAAhQMAIcMBAQCgAgAhxAEBAKACACHFASAAhQMAIcYBIACGAwAhxwFAAPoCACERBAAAzAMAIAUAAM0DACAKAADQAwAgDAAAzwMAIA4AAM4DACCYAQEAAAABnQFAAAAAAZ4BQAAAAAGrAQEAAAABwAEBAAAAAcEBAQAAAAHCASAAAAABwwEBAAAAAcQBAQAAAAHFASAAAAABxgEgAAAAAccBQAAAAAECAAAAAQAgGwAAjQQAIAkDAADpAgAgDAAA6gIAIJgBAQAAAAGaAQEAAAABnQFAAAAAAZ4BQAAAAAGqAQEAAAABqwEBAAAAAa0BAAAArQECAgAAAA0AIBsAAI8EACADAAAAKwAgGwAAjQQAIBwAAJMEACATAAAAKwAgBAAAhwMAIAUAAIgDACAKAACLAwAgDAAAigMAIA4AAIkDACAUAACTBAAgmAEBAKACACGdAUAAogIAIZ4BQACiAgAhqwEBAKsCACHAAQEAoAIAIcEBAQCgAgAhwgEgAIUDACHDAQEAoAIAIcQBAQCgAgAhxQEgAIUDACHGASAAhgMAIccBQAD6AgAhEQQAAIcDACAFAACIAwAgCgAAiwMAIAwAAIoDACAOAACJAwAgmAEBAKACACGdAUAAogIAIZ4BQACiAgAhqwEBAKsCACHAAQEAoAIAIcEBAQCgAgAhwgEgAIUDACHDAQEAoAIAIcQBAQCgAgAhxQEgAIUDACHGASAAhgMAIccBQAD6AgAhAwAAAAsAIBsAAI8EACAcAACWBAAgCwAAAAsAIAMAAK0CACAMAACuAgAgFAAAlgQAIJgBAQCgAgAhmgEBAKACACGdAUAAogIAIZ4BQACiAgAhqgEBAKsCACGrAQEAqwIAIa0BAACsAq0BIgkDAACtAgAgDAAArgIAIJgBAQCgAgAhmgEBAKACACGdAUAAogIAIZ4BQACiAgAhqgEBAKsCACGrAQEAqwIAIa0BAACsAq0BIgcEBgIFCgMKIgYLAAoMIQUNIwgODgQBAwABAQMAAQQDAAELAAkMEgUNHggGAwABBhMFBxQFCAAEChgGCwAHAgMAAQkABQIHGQAKGgACAwABCAAEAgwfAA0gAAYEJAAFJQAKKAAMJwANKQAOJgAAAAADCwAPIQAQIgARAAAAAwsADyEAECIAEQEDAAEBAwABAwsAFiEAFyIAGAAAAAMLABYhABciABgBAwABAQMAAQMLAB0hAB4iAB8AAAADCwAdIQAeIgAfAAAAAwsAJSEAJiIAJwAAAAMLACUhACYiACcDAwABBpABBQgABAMDAAEGlgEFCAAEAwsALCEALSIALgAAAAMLACwhAC0iAC4CAwABCQAFAgMAAQkABQMLADMhADQiADUAAAADCwAzIQA0IgA1AQMAAQEDAAEDCwA6IQA7IgA8AAAAAwsAOiEAOyIAPAIDAAEIAAQCAwABCAAEAwsAQSEAQiIAQwAAAAMLAEEhAEIiAEMPAgEQKgERLQESLgETLwEVMQEWMwsXNAwYNgEZOAsaOQ0dOgEeOwEfPAsjPw4kQBIlQQImQgInQwIoRAIpRQIqRwIrSQssShMtTAIuTgsvTxQwUAIxUQIyUgszVRU0Vhk1VwM2WAM3WQM4WgM5WwM6XQM7Xws8YBo9YgM-ZAs_ZRtAZgNBZwNCaAtDaxxEbCBFbiFGbyFHciFIcyFJdCFKdiFLeAtMeSJNeyFOfQtPfiNQfyFRgAEhUoEBC1OEASRUhQEoVYYBBVaHAQVXiAEFWIkBBVmKAQVajAEFW44BC1yPASldkgEFXpQBC1-VASpglwEFYZgBBWKZAQtjnAErZJ0BL2WeAQZmnwEGZ6ABBmihAQZpogEGaqQBBmumAQtspwEwbakBBm6rAQtvrAExcK0BBnGuAQZyrwELc7IBMnSzATZ1tAEEdrUBBHe2AQR4twEEebgBBHq6AQR7vAELfL0BN32_AQR-wQELf8IBOIABwwEEgQHEAQSCAcUBC4MByAE5hAHJAT2FAcoBCIYBywEIhwHMAQiIAc0BCIkBzgEIigHQAQiLAdIBC4wB0wE-jQHVAQiOAdcBC48B2AE_kAHZAQiRAdoBCJIB2wELkwHeAUCUAd8BRA"
};
async function decodeBase64AsWasm(wasmBase64) {
  const { Buffer } = await import("buffer");
  const wasmArray = Buffer.from(wasmBase64, "base64");
  return new WebAssembly.Module(wasmArray);
}
config.compilerWasm = {
  getRuntime: async () => await import("@prisma/client/runtime/query_compiler_fast_bg.postgresql.mjs"),
  getQueryCompilerWasmModule: async () => {
    const { wasm } = await import("@prisma/client/runtime/query_compiler_fast_bg.postgresql.wasm-base64.mjs");
    return await decodeBase64AsWasm(wasm);
  },
  importName: "./query_compiler_fast_bg.js"
};
function getPrismaClientClass() {
  return runtime.getPrismaClient(config);
}

// src/generated/prisma/internal/prismaNamespace.ts
import * as runtime2 from "@prisma/client/runtime/client";
var getExtensionContext = runtime2.Extensions.getExtensionContext;
var NullTypes2 = {
  DbNull: runtime2.NullTypes.DbNull,
  JsonNull: runtime2.NullTypes.JsonNull,
  AnyNull: runtime2.NullTypes.AnyNull
};
var TransactionIsolationLevel = runtime2.makeStrictEnum({
  ReadUncommitted: "ReadUncommitted",
  ReadCommitted: "ReadCommitted",
  RepeatableRead: "RepeatableRead",
  Serializable: "Serializable"
});
var defineExtension = runtime2.Extensions.defineExtension;

// src/generated/prisma/client.ts
globalThis["__dirname"] = path.dirname(fileURLToPath(import.meta.url));
var PrismaClient = getPrismaClientClass();

// src/app/lib/prisma.ts
var connectionString = `${process.env.DATABASE_URL}`;
var adapter = new PrismaPg({ connectionString });
var prisma = new PrismaClient({ adapter });

// src/app/modules/post/post.service.ts
var createPost = async (payload, userId) => {
  console.log(payload);
  const post = await prisma.post.create({
    data: {
      ...payload,
      userId
    }
  });
  return post;
};
var getAllPosts = async () => {
  const posts = await prisma.post.findMany({
    where: {
      privacy: Privacy.PUBLIC
    },
    include: {
      user: {
        select: {
          name: true,
          image: true
        }
      },
      postReactions: {
        include: {
          user: {
            select: {
              name: true,
              image: true
            }
          }
        }
      },
      comments: {
        include: {
          user: {
            select: {
              name: true,
              image: true
            }
          },
          commentReactions: {
            include: {
              user: {
                select: {
                  name: true,
                  image: true
                }
              }
            }
          },
          _count: {
            select: {
              commentReactions: true
            }
          }
        },
        orderBy: {
          createdAt: "asc"
        }
      },
      _count: {
        select: {
          comments: true,
          postReactions: true
        }
      }
    },
    orderBy: {
      createdAt: "desc"
    }
  });
  return posts;
};
var updatePost = async (id, payload, userId) => {
  const post = await prisma.post.update({
    where: {
      id,
      userId
    },
    data: payload
  });
  return post;
};
var deletePost = async (id, userId) => {
  const post = await prisma.post.delete({
    where: {
      id,
      userId
    }
  });
  return post;
};
var PostService = {
  createPost,
  getAllPosts,
  updatePost,
  deletePost
};

// src/shared/sendResponse.ts
var sendResponse = (res, data) => {
  res.status(data?.statusCode).json({
    success: true,
    message: data?.message,
    data: data?.data ?? null
  });
};
var sendResponse_default = sendResponse;

// src/app/modules/post/post.controller.ts
import { StatusCodes } from "http-status-codes";
var createPost2 = catchAsync(async (req, res) => {
  const payload = req.body;
  const userId = req.user?.id;
  const result = await PostService.createPost(payload, userId);
  sendResponse_default(res, {
    statusCode: StatusCodes.CREATED,
    message: "Post created successfully",
    data: result
  });
});
var getAllPosts2 = catchAsync(async (req, res) => {
  const result = await PostService.getAllPosts();
  sendResponse_default(res, {
    statusCode: StatusCodes.OK,
    message: "Posts retrieved successfully",
    data: result
  });
});
var updatePost2 = catchAsync(async (req, res) => {
  const { id } = req.params;
  const payload = req.body;
  const userId = req.user?.id;
  const result = await PostService.updatePost(id, payload, userId);
  sendResponse_default(res, {
    statusCode: StatusCodes.OK,
    message: "Post updated successfully",
    data: result
  });
});
var deletePost2 = catchAsync(async (req, res) => {
  const { id } = req.params;
  const userId = req.user?.id;
  const result = await PostService.deletePost(id, userId);
  sendResponse_default(res, {
    statusCode: StatusCodes.OK,
    message: "Post deleted successfully",
    data: result
  });
});
var PostController = {
  createPost: createPost2,
  getAllPosts: getAllPosts2,
  updatePost: updatePost2,
  deletePost: deletePost2
};

// src/app/lib/auth.ts
import { betterAuth } from "better-auth";
import { prismaAdapter } from "better-auth/adapters/prisma";
var auth = betterAuth({
  database: prismaAdapter(prisma, {
    provider: "postgresql"
  }),
  trustedOrigins: [process.env.APP_URL],
  emailAndPassword: {
    enabled: true,
    autoSignIn: true,
    requireEmailVerification: false
  },
  user: {
    additionalFields: {
      role: {
        type: "string",
        required: true,
        defaultValue: Role.USER
      },
      status: {
        type: "string",
        required: true,
        defaultValue: "ACTIVE"
      },
      changePassword: {
        type: "boolean",
        required: true,
        defaultValue: false
      },
      isDeleted: {
        type: "boolean",
        returned: true,
        defaultValue: false
      },
      deletedAt: {
        type: "date",
        returned: false,
        defaultValue: null
      }
    }
  },
  cookies: {
    secure: true,
    sameSite: "none"
  }
});

// src/middlewares/authMiddleware.ts
var authMiddleware = (...roles) => {
  return async (req, res, next) => {
    try {
      const token = req.headers.cookie;
      if (!token) {
        return res.status(401).json({
          success: false,
          message: "Unauthorized - No cookie found"
        });
      }
      const session = await auth.api.getSession({
        headers: req.headers
      });
      console.log("session backend =============================", session);
      if (!session || !session.user) {
        return res.status(401).json({
          success: false,
          message: "Unauthorized - Invalid session"
        });
      }
      req.user = {
        id: session?.user?.id,
        email: session?.user?.email,
        name: session?.user?.name,
        role: session?.user?.role,
        emailVerified: session?.user?.emailVerified,
        image: session?.user?.image ?? null
      };
      if (roles.length && !roles.includes(req.user.role)) {
        return res.status(403).json({
          success: false,
          message: "Forbidden - Insufficient permission"
        });
      }
      next();
    } catch (error) {
      console.error("Auth Middleware Error:", error);
      return res.status(500).json({
        success: false,
        message: "Authentication failed"
      });
    }
  };
};
var authMiddleware_default = authMiddleware;

// src/app/modules/post/post.routes.ts
var router = Router();
router.post("/", authMiddleware_default(Role.USER, Role.ADMIN), PostController.createPost);
router.get("/", PostController.getAllPosts);
router.put("/:id", authMiddleware_default(Role.USER, Role.ADMIN), PostController.updatePost);
router.delete("/:id", authMiddleware_default(Role.USER, Role.ADMIN), PostController.deletePost);
var PostRoutes = router;

// src/app/modules/comment/comment.routes.ts
import { Router as Router2 } from "express";

// src/app/modules/comment/comment.controller.ts
import { StatusCodes as StatusCodes2 } from "http-status-codes";

// src/app/modules/comment/comment.service.ts
var createComment = async (payload, postId, userId) => {
  const comment = await prisma.comment.create({
    data: {
      ...payload,
      postId,
      userId
    }
  });
  return comment;
};
var updateComment = async (commentId, payload) => {
  const comment = await prisma.comment.update({
    where: {
      id: commentId
    },
    data: payload
  });
  return comment;
};
var deleteComment = async (commentId, userId) => {
  const comment = await prisma.comment.delete({
    where: {
      id: commentId,
      userId
    }
  });
  return comment;
};
var CommentService = {
  createComment,
  updateComment,
  deleteComment
};

// src/app/modules/comment/comment.controller.ts
var createComment2 = catchAsync(async (req, res) => {
  const { postId } = req.params;
  const userId = req.user?.id;
  const payload = req.body;
  const result = await CommentService.createComment(payload, postId, userId);
  sendResponse_default(res, {
    statusCode: StatusCodes2.CREATED,
    message: "Comment created successfully",
    data: result
  });
});
var updateComment2 = catchAsync(async (req, res) => {
  const { commentId } = req.params;
  const payload = req.body;
  const result = await CommentService.updateComment(commentId, payload);
  sendResponse_default(res, {
    statusCode: StatusCodes2.OK,
    message: "Comment updated successfully",
    data: result
  });
});
var deleteComment2 = catchAsync(async (req, res) => {
  const { commentId } = req.params;
  const userId = req.user?.id;
  const result = await CommentService.deleteComment(commentId, userId);
  sendResponse_default(res, {
    statusCode: StatusCodes2.OK,
    message: "Comment deleted successfully",
    data: result
  });
});
var CommentController = {
  createComment: createComment2,
  updateComment: updateComment2,
  deleteComment: deleteComment2
};

// src/app/modules/comment/comment.routes.ts
var router2 = Router2();
router2.post("/:postId", authMiddleware_default(Role.USER, Role.ADMIN), CommentController.createComment);
router2.put("/:commentId", authMiddleware_default(Role.USER, Role.ADMIN), CommentController.updateComment);
router2.delete("/:commentId", authMiddleware_default(Role.USER, Role.ADMIN), CommentController.deleteComment);
var CommentRoutes = router2;

// src/app/modules/commentReactions/commentReactions.routes.ts
import { Router as Router3 } from "express";

// src/app/modules/commentReactions/commentReactions.controller.ts
import { StatusCodes as StatusCodes4 } from "http-status-codes";

// src/app/modules/commentReactions/commentReactions.service.ts
import { StatusCodes as StatusCodes3 } from "http-status-codes";

// src/app/errors/AppError.ts
var AppError = class extends Error {
  statusCode;
  constructor(statusCode, message) {
    super(message);
    this.statusCode = statusCode;
    Error.captureStackTrace(this, this.constructor);
  }
};

// src/app/modules/commentReactions/commentReactions.service.ts
var createCommentReaction = async (commentId, userId, payload) => {
  const existingReaction = await prisma.commentReactions.findFirst({
    where: {
      commentId,
      userId
    }
  });
  if (existingReaction) {
    throw new AppError(
      StatusCodes3.BAD_REQUEST,
      "You have already reacted to this comment"
    );
  }
  const createReaction = await prisma.commentReactions.create({
    data: {
      commentId,
      userId,
      type: payload.type
    }
  });
  return createReaction;
};
var removeCommentReaction = async (commentId, userId) => {
  const deletedReaction = await prisma.commentReactions.delete({
    where: {
      id: commentId,
      userId
    }
  });
  return deletedReaction;
};
var commentReactionsService = {
  createCommentReaction,
  removeCommentReaction
};

// src/app/modules/commentReactions/commentReactions.controller.ts
var createCommentReaction2 = catchAsync(async (req, res) => {
  const { commentId } = req.params;
  const payload = req.body;
  const userId = req.user?.id;
  const commentReaction = await commentReactionsService.createCommentReaction(commentId, userId, payload);
  sendResponse_default(res, {
    statusCode: StatusCodes4.CREATED,
    message: "Comment reaction created successfully",
    data: commentReaction
  });
});
var removeCommentReaction2 = catchAsync(async (req, res) => {
  const { commentId } = req.params;
  const userId = req.user?.id;
  const commentReaction = await commentReactionsService.removeCommentReaction(commentId, userId);
  sendResponse_default(res, {
    statusCode: StatusCodes4.OK,
    message: "Comment reaction removed successfully",
    data: commentReaction
  });
});
var commentReactionsController = {
  createCommentReaction: createCommentReaction2,
  removeCommentReaction: removeCommentReaction2
};

// src/app/modules/commentReactions/commentReactions.routes.ts
var router3 = Router3();
router3.post("/:commentId", authMiddleware_default(Role.USER, Role.ADMIN), commentReactionsController.createCommentReaction);
router3.delete("/:commentId", authMiddleware_default(Role.USER, Role.ADMIN), commentReactionsController.removeCommentReaction);
var commentReactionsRoutes = router3;

// src/app/modules/postReactions/postReactions.routes.ts
import { Router as Router4 } from "express";

// src/app/modules/postReactions/postReactions.controller.ts
import { StatusCodes as StatusCodes5 } from "http-status-codes";

// src/app/modules/postReactions/postReactions.service.ts
var createPostReaction = async (payload, userId, postId) => {
  const postReaction = await prisma.postReactions.create({
    data: {
      postId,
      userId,
      reaction: payload?.reaction
    }
  });
  return postReaction;
};
var removePostReaction = async (userId, postId) => {
  const postReaction = await prisma.postReactions.delete({
    where: {
      userId_postId: {
        userId,
        postId
      }
    }
  });
  return postReaction;
};
var PostReactionsService = {
  createPostReaction,
  removePostReaction
};

// src/app/modules/postReactions/postReactions.controller.ts
var createPostReaction2 = catchAsync(async (req, res) => {
  const payload = req.body;
  const userId = req.user?.id;
  const postId = req.params.postId;
  const postReaction = await PostReactionsService.createPostReaction(payload, userId, postId);
  sendResponse_default(res, {
    statusCode: StatusCodes5.CREATED,
    message: "Post reaction created successfully",
    data: postReaction
  });
});
var removePostReaction2 = catchAsync(async (req, res) => {
  const userId = req.user?.id;
  const postId = req.params.postId;
  const postReaction = await PostReactionsService.removePostReaction(userId, postId);
  sendResponse_default(res, {
    statusCode: StatusCodes5.OK,
    message: "Post reaction removed successfully",
    data: postReaction
  });
});
var PostReactionsController = {
  createPostReaction: createPostReaction2,
  removePostReaction: removePostReaction2
};

// src/app/modules/postReactions/postReactions.routes.ts
var router4 = Router4();
router4.post("/:postId", authMiddleware_default(Role.USER, Role.ADMIN), PostReactionsController.createPostReaction);
router4.delete("/:postId", authMiddleware_default(Role.USER, Role.ADMIN), PostReactionsController.removePostReaction);
var PostReactionsRoutes = router4;

// src/app/routes/index.ts
var router5 = Router5();
router5.use("/posts", PostRoutes);
router5.use("/comments", CommentRoutes);
router5.use("/comment-reactions", commentReactionsRoutes);
router5.use("/post-reactions", PostReactionsRoutes);
var IndexRoutes = router5;

// src/middlewares/globalErrorHandler.ts
var globalErrorHandler = (err, req, res, next) => {
  const statusCode = err.statusCode || 500;
  const message = err.message || "Something went wrong";
  res.status(statusCode).json({
    success: false,
    message
  });
};
var globalErrorHandler_default = globalErrorHandler;

// src/app.ts
import cors from "cors";
import cookieParser from "cookie-parser";
var app = express();
app.use(express.json());
app.use(cookieParser());
app.use(cors({
  origin: process.env.APP_URL,
  // client side url
  credentials: true
}));
app.get("/", async (req, res) => {
  res.send("Buddy script server is running!");
});
app.all("/api/auth/*splat", toNodeHandler(auth));
app.use("/api/v1", IndexRoutes);
app.use(globalErrorHandler_default);
var app_default = app;

// src/index.ts
var index_default = app_default;
export {
  index_default as default
};
